//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Fill_Up_App.FillUpWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FillUpWebServiceSoap", Namespace="http://dotnet-revanth.blogspot.com/webservices")]
    public partial class FillUpWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BarNameAdaptationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBarReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarRateAverageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsBarNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback BestBarRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindBetterBarNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FillUpWebService() {
            this.Url = "http://fillupapp.azurewebsites.net/FillUpWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BarNameAdaptationCompletedEventHandler BarNameAdaptationCompleted;
        
        /// <remarks/>
        public event AddBarReviewCompletedEventHandler AddBarReviewCompleted;
        
        /// <remarks/>
        public event BarRateAverageCompletedEventHandler BarRateAverageCompleted;
        
        /// <remarks/>
        public event ValidationCompletedEventHandler ValidationCompleted;
        
        /// <remarks/>
        public event IsBarNewCompletedEventHandler IsBarNewCompleted;
        
        /// <remarks/>
        public event BestBarRateCompletedEventHandler BestBarRateCompleted;
        
        /// <remarks/>
        public event StatsCompletedEventHandler StatsCompleted;
        
        /// <remarks/>
        public event FindBetterBarNameCompletedEventHandler FindBetterBarNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/BarNameAdaptation", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BarNameAdaptation(string barName) {
            object[] results = this.Invoke("BarNameAdaptation", new object[] {
                        barName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BarNameAdaptationAsync(string barName) {
            this.BarNameAdaptationAsync(barName, null);
        }
        
        /// <remarks/>
        public void BarNameAdaptationAsync(string barName, object userState) {
            if ((this.BarNameAdaptationOperationCompleted == null)) {
                this.BarNameAdaptationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarNameAdaptationOperationCompleted);
            }
            this.InvokeAsync("BarNameAdaptation", new object[] {
                        barName}, this.BarNameAdaptationOperationCompleted, userState);
        }
        
        private void OnBarNameAdaptationOperationCompleted(object arg) {
            if ((this.BarNameAdaptationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarNameAdaptationCompleted(this, new BarNameAdaptationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/AddBarReview", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddBarReview(string barName, int ratingOfBar) {
            object[] results = this.Invoke("AddBarReview", new object[] {
                        barName,
                        ratingOfBar});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddBarReviewAsync(string barName, int ratingOfBar) {
            this.AddBarReviewAsync(barName, ratingOfBar, null);
        }
        
        /// <remarks/>
        public void AddBarReviewAsync(string barName, int ratingOfBar, object userState) {
            if ((this.AddBarReviewOperationCompleted == null)) {
                this.AddBarReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBarReviewOperationCompleted);
            }
            this.InvokeAsync("AddBarReview", new object[] {
                        barName,
                        ratingOfBar}, this.AddBarReviewOperationCompleted, userState);
        }
        
        private void OnAddBarReviewOperationCompleted(object arg) {
            if ((this.AddBarReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBarReviewCompleted(this, new AddBarReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/BarRateAverage", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double BarRateAverage(string barName, int ratingOfBar) {
            object[] results = this.Invoke("BarRateAverage", new object[] {
                        barName,
                        ratingOfBar});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void BarRateAverageAsync(string barName, int ratingOfBar) {
            this.BarRateAverageAsync(barName, ratingOfBar, null);
        }
        
        /// <remarks/>
        public void BarRateAverageAsync(string barName, int ratingOfBar, object userState) {
            if ((this.BarRateAverageOperationCompleted == null)) {
                this.BarRateAverageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarRateAverageOperationCompleted);
            }
            this.InvokeAsync("BarRateAverage", new object[] {
                        barName,
                        ratingOfBar}, this.BarRateAverageOperationCompleted, userState);
        }
        
        private void OnBarRateAverageOperationCompleted(object arg) {
            if ((this.BarRateAverageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarRateAverageCompleted(this, new BarRateAverageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/Validation", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Validation(int ratingOfBar, string barName) {
            object[] results = this.Invoke("Validation", new object[] {
                        ratingOfBar,
                        barName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidationAsync(int ratingOfBar, string barName) {
            this.ValidationAsync(ratingOfBar, barName, null);
        }
        
        /// <remarks/>
        public void ValidationAsync(int ratingOfBar, string barName, object userState) {
            if ((this.ValidationOperationCompleted == null)) {
                this.ValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidationOperationCompleted);
            }
            this.InvokeAsync("Validation", new object[] {
                        ratingOfBar,
                        barName}, this.ValidationOperationCompleted, userState);
        }
        
        private void OnValidationOperationCompleted(object arg) {
            if ((this.ValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidationCompleted(this, new ValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/IsBarNew", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsBarNew(string barName) {
            object[] results = this.Invoke("IsBarNew", new object[] {
                        barName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsBarNewAsync(string barName) {
            this.IsBarNewAsync(barName, null);
        }
        
        /// <remarks/>
        public void IsBarNewAsync(string barName, object userState) {
            if ((this.IsBarNewOperationCompleted == null)) {
                this.IsBarNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsBarNewOperationCompleted);
            }
            this.InvokeAsync("IsBarNew", new object[] {
                        barName}, this.IsBarNewOperationCompleted, userState);
        }
        
        private void OnIsBarNewOperationCompleted(object arg) {
            if ((this.IsBarNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsBarNewCompleted(this, new IsBarNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/BestBarRate", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BestBarRate() {
            object[] results = this.Invoke("BestBarRate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BestBarRateAsync() {
            this.BestBarRateAsync(null);
        }
        
        /// <remarks/>
        public void BestBarRateAsync(object userState) {
            if ((this.BestBarRateOperationCompleted == null)) {
                this.BestBarRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBestBarRateOperationCompleted);
            }
            this.InvokeAsync("BestBarRate", new object[0], this.BestBarRateOperationCompleted, userState);
        }
        
        private void OnBestBarRateOperationCompleted(object arg) {
            if ((this.BestBarRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BestBarRateCompleted(this, new BestBarRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/Stats", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Stats() {
            object[] results = this.Invoke("Stats", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StatsAsync() {
            this.StatsAsync(null);
        }
        
        /// <remarks/>
        public void StatsAsync(object userState) {
            if ((this.StatsOperationCompleted == null)) {
                this.StatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatsOperationCompleted);
            }
            this.InvokeAsync("Stats", new object[0], this.StatsOperationCompleted, userState);
        }
        
        private void OnStatsOperationCompleted(object arg) {
            if ((this.StatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatsCompleted(this, new StatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dotnet-revanth.blogspot.com/webservices/FindBetterBarName", RequestNamespace="http://dotnet-revanth.blogspot.com/webservices", ResponseNamespace="http://dotnet-revanth.blogspot.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindBetterBarName(string name, int rating) {
            object[] results = this.Invoke("FindBetterBarName", new object[] {
                        name,
                        rating});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FindBetterBarNameAsync(string name, int rating) {
            this.FindBetterBarNameAsync(name, rating, null);
        }
        
        /// <remarks/>
        public void FindBetterBarNameAsync(string name, int rating, object userState) {
            if ((this.FindBetterBarNameOperationCompleted == null)) {
                this.FindBetterBarNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindBetterBarNameOperationCompleted);
            }
            this.InvokeAsync("FindBetterBarName", new object[] {
                        name,
                        rating}, this.FindBetterBarNameOperationCompleted, userState);
        }
        
        private void OnFindBetterBarNameOperationCompleted(object arg) {
            if ((this.FindBetterBarNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindBetterBarNameCompleted(this, new FindBetterBarNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BarNameAdaptationCompletedEventHandler(object sender, BarNameAdaptationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarNameAdaptationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarNameAdaptationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddBarReviewCompletedEventHandler(object sender, AddBarReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBarReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBarReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BarRateAverageCompletedEventHandler(object sender, BarRateAverageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarRateAverageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarRateAverageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ValidationCompletedEventHandler(object sender, ValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsBarNewCompletedEventHandler(object sender, IsBarNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsBarNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsBarNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BestBarRateCompletedEventHandler(object sender, BestBarRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BestBarRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BestBarRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void StatsCompletedEventHandler(object sender, StatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void FindBetterBarNameCompletedEventHandler(object sender, FindBetterBarNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindBetterBarNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindBetterBarNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591